Repository SuperTux/supertux, pull requests merged in 2018-07, with the labels that each got.

#865 Moved Object name property parsing to GameObject class
  src/badguy/dispenser.cpp
  src/badguy/willowisp.cpp
  src/object/ambient_sound.cpp
  src/object/background.cpp
  src/object/candle.cpp
  src/object/gradient.cpp
  src/object/invisible_wall.cpp
  src/object/lantern.cpp
  src/object/level_time.cpp
  src/object/moving_sprite.cpp
  src/object/platform.cpp
  src/object/rock.cpp
  src/object/rusty_trampoline.cpp
  src/object/scripted_object.cpp
  src/object/thunderstorm.cpp
  src/object/tilemap.cpp
  src/object/torch.cpp
  src/object/trampoline.cpp
  src/object/wind.cpp
  src/supertux/game_object.cpp
  src/supertux/game_object.hpp
  src/supertux/moving_object.cpp
  src/supertux/moving_object.hpp
Labels: category:code, status:in-progress, type:patch

#654 Show flying leaf animation for Walking Leaf and Leaf Shot
  data/images/objects/particles/leafshot.sprite
  data/images/objects/particles/walkingleaf-0.png
  data/images/objects/particles/walkingleaf-1.png
  data/images/objects/particles/walkingleaf-2.png
  data/images/objects/particles/walkingleaf-3.png
  data/images/objects/particles/walkingleaf.sprite
  src/badguy/kamikazesnowball.cpp
  src/badguy/kamikazesnowball.hpp
  src/badguy/poisonivy.cpp
  src/badguy/walkingleaf.cpp
  src/object/moving_sprite.cpp
  src/object/moving_sprite.hpp
Labels: category:code, category:design, type:patch

#882 README: Various Improvements [1/n]
  README.md
Labels: category:meta, involves:documentation, priority:high

#883 README: central Community section for getting in touch
  CONTRIBUTING.md
  INSTALL.md
  README.md
Labels: category:meta, involves:documentation, priority:high

#639 Coding Standards Changes
  CODINGSTYLE
  CODINGSTYLE.md
Labels: category:code, category:meta, status:in-progress, status:needs-discussion, type:idea
