Repository SuperTux/supertux, pull requests merged in 2018-06, with the labels that each got.

#772 ScriptTrigger: add oneshot option
  src/trigger/scripttrigger.cpp
  src/trigger/scripttrigger.hpp
Labels: category:code, involves:scripting, type:feature

#845 Added invincibility retaining code between doors
  src/supertux/game_session.cpp
  src/supertux/game_session.hpp
  src/trigger/door.cpp
Labels: category:code, status:needs-review, type:patch

#849 Fixed Travis CI problems caused by PR #845
  src/supertux/game_session.cpp
Labels: category:code, type:patch
