Repository SuperTux/supertux, pull requests merged in 2020-06, with the labels that each got.

#1433 Crash fix: handle dragging a selection rectangle up/left correctly.
  src/editor/overlay_widget.cpp
Labels: category:code, status:needs-review, type:bug

#1434 When dragging tile selections upwards or to the left, fix offset math.
  src/editor/overlay_widget.cpp
Labels: category:code, status:needs-review

#1435 Make the other Rectf ctor also assert that size can't be negative.
  src/math/rectf.hpp
Labels: category:code, status:needs-review

#1436 First update editor widgets, then flush deleted objects away.
  src/editor/editor.cpp
Labels: category:code, type:bug

#1437 Fix assertion failure in triangle drawing on the SDL backend.
  src/video/sdl/sdl_painter.cpp
Labels: category:code, status:needs-review

#765 Spelling: Fractions for tiles
  src/supertux/menu/editor_menu.cpp
Labels: category:code, status:needs-work

#1431 Add sideways icecrushers
  src/object/icecrusher.cpp
  src/object/icecrusher.hpp
Labels: category:code, category:design, involves:editor, involves:functionality, involves:physics, status:in-progress, type:feature
