Repository SuperTux/supertux, pull requests merged in 2020-01, with the labels that each got.

#1254 Fix broken powerup path
  src/object/powerup.cpp
Labels: status:needs-work

#1323 New Snow Castle tileset
  data/images/tiles.strf
  data/images/tiles/castle/snowcastle.png
Labels: category:design

#1319 Trampolines from bonus block no longer hurt Tux
  src/object/bonus_block.cpp
Labels: category:code

#1324 New arctic background
  data/images/background/antarctic/arcticmountains.png
Labels: category:design

#1271 Use green font for perfect level stats
  src/supertux/colorscheme.cpp
  src/supertux/game_session.cpp
  src/supertux/levelintro.cpp
  src/supertux/levelintro.hpp
  src/supertux/statistics.cpp
  src/supertux/statistics.hpp
Labels: category:code, category:design, status:awaiting-merge
