Repository SuperTux/supertux, pull requests merged in 2022-12, with the labels that each got.

#2345 Quick fix (2)
  src/badguy/mriceblock.cpp
  src/gui/menu_badguy_select.cpp
Labels: involves:editor, category:code, type:bugfix

#1722 Editor: Put tiles without holes when holding the left mouse button
  src/editor/overlay_widget.cpp
  src/editor/overlay_widget.hpp
Labels: involves:editor, category:code

#2368 Add video system menu
  src/gui/dialog.hpp
  src/supertux/menu/menu_storage.cpp
  src/supertux/menu/menu_storage.hpp
  src/supertux/menu/options_menu.cpp
  src/supertux/menu/video_system_menu.cpp
  src/supertux/menu/video_system_menu.hpp
  src/video/video_system.cpp
  src/video/video_system.hpp
Labels: type:feature, category:code, status:needs-review
