Repository SuperTux/supertux, pull requests merged in 2022-10, with the labels that each got.

#2267 Add notification GUI item + check for new releases
  src/gui/menu_manager.cpp
  src/gui/menu_manager.hpp
  src/gui/notification.cpp
  src/gui/notification.hpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/main.cpp
  src/supertux/main.hpp
  src/supertux/menu/download_dialog.cpp
  src/supertux/menu/download_dialog.hpp
  src/supertux/menu/options_menu.cpp
Labels: status:needs-discussion, type:feature

#2302 Separate dispenser sprite files + remove rocker launcher
  src/badguy/badguy.cpp
  src/badguy/dispenser.cpp
  src/badguy/dispenser.hpp
  src/supertux/direction.cpp
Labels: involves:editor, category:code, status:needs-review, status:conditional

#2263 Remove hardcoded tile IDs for electrocution
  src/object/thunderstorm.cpp
  src/object/thunderstorm.hpp
  src/supertux/tile_set.cpp
  src/supertux/tile_set.hpp
  src/supertux/tile_set_parser.cpp
Labels: status:conditional, type:bugfix

#2319 Fix MagicBlock::m_center not being updated after level flip
  src/object/magicblock.cpp
Labels: category:code, type:bugfix

#2317 Add support for changing mobile controls scale
  src/control/mobile_controller.cpp
  src/control/mobile_controller.hpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/menu/options_menu.cpp
  src/supertux/menu/options_menu.hpp
Labels: type:feature, category:code
