Repository SuperTux/supertux, pull requests merged in 2023-06, with the labels that each got.

#2481 Add corrupted variant of Snail
  data/images/creatures/snail/corrupted/corrupted_snail.sprite
  data/images/creatures/snail/corrupted/guard-0.png
  data/images/creatures/snail/corrupted/guard-1.png
  data/images/creatures/snail/corrupted/guard-2.png
  data/images/creatures/snail/corrupted/guard-3.png
  data/images/creatures/snail/corrupted/guard-4.png
  data/images/creatures/snail/corrupted/guard-5.png
  data/images/creatures/snail/corrupted/guard-6.png
  data/images/creatures/snail/corrupted/guard-7.png
  data/images/creatures/snail/corrupted/left-0.png
  data/images/creatures/snail/corrupted/left-1.png
  data/images/creatures/snail/corrupted/left-2.png
  data/images/creatures/snail/corrupted/left-3.png
  data/images/creatures/snail/corrupted/left-4.png
  data/images/creatures/snail/corrupted/left-5.png
  data/images/creatures/snail/corrupted/left-6.png
  data/images/creatures/snail/corrupted/left-7.png
  data/images/creatures/snail/corrupted/rotate-0.png
  data/images/creatures/snail/corrupted/rotate-1.png
  data/images/creatures/snail/corrupted/rotate-2.png
  data/images/creatures/snail/corrupted/rotate-3.png
  data/images/creatures/snail/corrupted/rotate-4.png
  data/images/creatures/snail/corrupted/rotate-5.png
  data/images/creatures/snail/corrupted/rotate-6.png
  data/images/creatures/snail/corrupted/rotate-7.png
  src/badguy/snail.cpp
  src/badguy/snail.hpp
Labels: type:feature, category:code, category:design, status:needs-review

#2463 Update HUD images and icons
  data/images/decal/halloween/spookytree1.png
  data/images/decal/halloween/tree.png
  data/images/engine/editor/hurtingplatform.png
  data/images/engine/editor/objects.stoi
  data/images/engine/editor/redo.png
  data/images/engine/editor/spritechange.png
  data/images/engine/editor/undo.png
  data/images/engine/hud/airarrow.png
  data/images/engine/hud/arrowdown.png
  data/images/engine/hud/badguy-icon.png
  data/images/engine/menu/score-backdrop.png
  data/images/engine/menu/scroll-down.png
  data/images/engine/menu/scroll-up.png
  data/images/engine/mobile/action.png
  data/images/engine/mobile/button.png
  data/images/engine/mobile/button.xcf
  data/images/engine/mobile/button_press.png
  data/images/engine/mobile/debug.png
  data/images/engine/mobile/direction.png
  data/images/engine/mobile/jump.png
  data/images/engine/mobile/pause.png
  data/images/worldmap/common/messagedot.png
  data/images/worldmap/common/specialtile.png
  data/images/worldmap/common/specialtile.sprite
  src/editor/worldmap_objects.cpp
Labels: category:design

#2351 Upgraded several background images
  data/images/background/antarctic/snow_bottom.png
  data/images/background/antarctic/snow_hills.png
  data/images/background/antarctic/snow_panorama.png
  data/images/background/antarctic/snowy_trees.png
  data/images/background/castle/corrupt_castle.png
  data/images/background/castle/corrupt_castle_pillar.png
  data/images/background/castle/forest_castle.png
  data/images/background/castle/forest_castle_pillar.png
  data/images/background/castle/ice_castle.png
  data/images/background/castle/ice_castle_pillar.png
  data/images/background/corrupted_forest/gh_forest_bottom.png
  data/images/background/corrupted_forest/gh_tree_back.png
  data/images/background/corrupted_forest/gh_tree_front.png
  data/images/background/corrupted_forest/test
  data/images/background/forest/forest_bottom.png
  data/images/background/forest/forest_panorama.png
  data/images/background/forest/tree_back.png
  data/images/background/forest/tree_front.png
  data/images/background/halloween/mountain.png
  data/images/background/halloween/mountain_panorama.png
  data/images/background/ice_cave/ice_cave_backwall.png
  data/images/background/ice_cave/ice_cave_front.png
  data/images/background/ice_cave/ice_cave_middle.png
  data/images/background/misc/skybox.png
  data/images/background/misc/skybox_night.png
  data/images/background/misc/vignette.png
  data/images/background/retro/arctis_icechunk.png
  data/images/background/retro/arctis_shore.png
  data/images/background/retro/arctis_skyline.png
  data/images/background/retro/cave_wall.png
  data/images/background/retro/cave_wood.png
  data/images/engine/menu/frame.png
  data/levels/bonus4/Deeper_Into_The_Mountains.stl
  data/levels/bonus4/Halloween_Fields.stl
  data/levels/bonus4/Its_Halloween_Time.stl
  data/levels/bonus4/Spooky_Mansion.stl
  data/levels/bonus4/Stormy_Night.stl
  data/levels/christmas2016/worldmap.stwm
  data/levels/halloween2014/halloween1.stl
  data/levels/halloween2014/halloween2.stl
  data/levels/halloween2014/halloween3.stl
  data/levels/halloween2014/mound.stl
  data/levels/halloween2014/pools.stl
  data/levels/halloween2014/worldmap.stwm
  data/levels/revenge_in_redmond/worldmap.stwm
Labels: category:design

#2320 Refactor undo/redo system to track separate object changes
  src/editor/bezier_marker.cpp
  src/editor/bezier_marker.hpp
  src/editor/editor.cpp
  src/editor/editor.hpp
  src/editor/layers_widget.cpp
  src/editor/layers_widget.hpp
  src/editor/marker_object.hpp
  src/editor/node_marker.cpp
  src/editor/node_marker.hpp
  src/editor/object_menu.cpp
  src/editor/overlay_widget.cpp
  src/editor/resize_marker.cpp
  src/editor/resize_marker.hpp
  src/editor/undo_manager.cpp
  src/editor/undo_manager.hpp
  src/object/path.cpp
  src/object/path.hpp
  src/object/path_gameobject.cpp
  src/object/path_gameobject.hpp
  src/object/platform.cpp
  src/object/platform.hpp
  src/supertux/game_object.cpp
  src/supertux/game_object.hpp
  src/supertux/game_object_factory.cpp
  src/supertux/game_object_factory.hpp
  src/supertux/game_object_manager.cpp
  src/supertux/game_object_manager.hpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/menu/editor_menu.cpp
  src/supertux/menu/editor_menu.hpp
  src/supertux/moving_object.cpp
  src/supertux/moving_object.hpp
  src/supertux/sector.cpp
Labels: involves:editor, type:feature, category:code, status:needs-review, type:bugfix

#2499 Add the ability to get player input from the scripting API.
  src/scripting/player.cpp
  src/scripting/player.hpp
  src/scripting/wrapper.cpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2496 Options for rock, portable trampoline, and potion bonus blocks.
  src/object/bonus_block.cpp
  src/object/bonus_block.hpp
Labels: involves:editor, type:feature, category:code

#2290 Add Conveyor Belt object
  data/images/engine/editor/objects.stoi
  data/images/objects/conveyor_belt/conveyor.sprite
  data/images/objects/conveyor_belt/conveyor_left0.png
  data/images/objects/conveyor_belt/conveyor_left1.png
  data/images/objects/conveyor_belt/conveyor_left2.png
  data/images/objects/conveyor_belt/conveyor_left3.png
  data/images/objects/conveyor_belt/conveyor_left4.png
  data/images/objects/conveyor_belt/conveyor_left5.png
  data/images/objects/conveyor_belt/conveyor_right0.png
  data/images/objects/conveyor_belt/conveyor_right1.png
  data/images/objects/conveyor_belt/conveyor_right2.png
  data/images/objects/conveyor_belt/conveyor_right3.png
  data/images/objects/conveyor_belt/conveyor_right4.png
  data/images/objects/conveyor_belt/conveyor_right5.png
  data/images/objects/conveyor_belt/conveyor_stopped.png
  src/badguy/walking_badguy.cpp
  src/badguy/walking_badguy.hpp
  src/object/conveyor_belt.cpp
  src/object/conveyor_belt.hpp
  src/scripting/conveyor_belt.cpp
  src/scripting/conveyor_belt.hpp
  src/scripting/wrapper.cpp
  src/scripting/wrapper.hpp
  src/scripting/wrapper.interface.hpp
  src/supertux/game_object_factory.cpp
Labels: status:in-progress, type:feature, category:code
