Repository SuperTux/supertux, pull requests merged in 2023-10, with the labels that each got.

#2651 Fix setting random seed to current time
  src/math/random.cpp
Labels: category:code, status:needs-review, type:bugfix

#2647 Unisolid hitboxes for objects
  src/collision/collision_object.cpp
  src/collision/collision_object.hpp
  src/collision/collision_system.cpp
  src/object/conveyor_belt.cpp
  src/object/moving_sprite.cpp
  src/sprite/sprite.cpp
  src/sprite/sprite.hpp
  src/sprite/sprite_data.cpp
  src/sprite/sprite_data.hpp
Labels: type:feature, category:code, status:needs-review, involves:physics

#2654 Fix editor world conflicts when browsing levels from a different world
  src/supertux/menu/editor_delete_level_menu.cpp
  src/supertux/menu/editor_delete_level_menu.hpp
  src/supertux/menu/editor_level_select_menu.cpp
  src/supertux/menu/editor_level_select_menu.hpp
  src/supertux/menu/editor_levelset_menu.cpp
  src/supertux/menu/editor_levelset_menu.hpp
  src/supertux/menu/editor_new_levelset_menu.cpp
  src/supertux/menu/menu_storage.cpp
  src/supertux/menu/menu_storage.hpp
Labels: involves:editor, category:code, status:needs-review, type:bugfix

#2660 Expose `get_filename` to scripting under `worldmap.settings`.
  src/scripting/worldmap_sector.cpp
  src/scripting/worldmap_sector.hpp
  src/scripting/wrapper.cpp
  src/worldmap/worldmap.cpp
  src/worldmap/worldmap.hpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2593 Use only default keybinds, when navigating menus
  src/control/keyboard_manager.cpp
Labels: category:code, status:needs-review, type:bugfix

#2665 Fix broken `load_worldmap` and `set_next_worldmap` scripting functions
  src/scripting/functions.cpp
  src/scripting/functions.hpp
  src/scripting/wrapper.cpp
  src/supertux/game_manager.cpp
  src/supertux/game_manager.hpp
Labels: category:code, involves:scripting, status:needs-review, type:bugfix

#2618 Fix build warnings
  src/badguy/walking_badguy.cpp
  src/gui/menu_manager.hpp
  src/object/key.cpp
  src/supertux/menu/options_menu.hpp
  src/supertux/object_factory.hpp
  src/video/video_system.cpp
Labels: category:code
