Repository SuperTux/supertux, pull requests merged in 2023-02, with the labels that each got.

#2388 Allow setting anchor offset for text object position
  src/object/text_object.cpp
  src/object/text_object.hpp
  src/scripting/text.cpp
  src/scripting/text.hpp
  src/scripting/text_array.cpp
  src/scripting/text_array.hpp
  src/scripting/wrapper.cpp
  src/trigger/text_area.cpp
  src/trigger/text_area.hpp
Labels: involves:functionality, type:feature, category:code, involves:scripting

#2229 Drag drop install addons
  src/addon/addon_manager.cpp
  src/addon/addon_manager.hpp
  src/gui/menu.hpp
  src/supertux/menu/addon_file_install_menu.cpp
  src/supertux/menu/addon_file_install_menu.hpp
  src/supertux/menu/addon_menu.cpp
  src/supertux/menu/addon_menu.hpp
  src/supertux/screen_manager.cpp
  src/util/file_system.cpp
  src/util/file_system.hpp
Labels: type:feature

#2338 Player behavior improvements
  data/images/creatures/tux/earth/statue.png
  data/images/creatures/tux/tux.sprite
  data/images/particles/rock-0.png
  data/images/particles/rock-1.png
  data/images/particles/rock-2.png
  data/images/particles/rock-3.png
  data/images/particles/rock-4.png
  data/images/particles/rock.sprite
  src/badguy/badguy.cpp
  src/object/block.cpp
  src/object/bumper.cpp
  src/object/explosion.cpp
  src/object/player.cpp
  src/object/player.hpp
  src/object/trampoline.cpp
  src/object/wind.cpp
Labels: involves:functionality, status:in-progress, type:feature, category:code, status:conditional
