Repository SuperTux/supertux, pull requests merged in 2023-11, with the labels that each got.

#2669 Fix enemy death script running twice if Tux slides into it.
  src/badguy/badguy.cpp
Labels: category:code, involves:scripting, status:needs-review, type:bugfix

#2596 Preserving players and grabbed objects between sectors
  src/object/key.cpp
  src/object/key.hpp
  src/object/player.cpp
  src/object/player.hpp
  src/supertux/game_object_manager.cpp
  src/supertux/game_object_manager.hpp
  src/supertux/game_session.cpp
  src/supertux/game_session.hpp
  src/supertux/level.cpp
  src/supertux/level.hpp
  src/supertux/level_parser.cpp
  src/supertux/sector.cpp
  src/trigger/door.cpp
Labels: type:feature, category:code, status:needs-review, type:bugfix

#2656 Change animation for Owl not carrying an object
  data/images/creatures/owl/owl.sprite
  src/badguy/owl.cpp
Labels: category:code, category:design, status:needs-review

#2683 Fix smart BadGuy movement on e.g. rocks
  src/badguy/badguy.cpp
  src/collision/collision_system.cpp
  src/collision/collision_system.hpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
Labels: category:code, status:needs-review, type:bugfix

#2687 Changing some display name for a couple badguys
  src/badguy/kamikazesnowball.hpp
  src/badguy/mrbomb.hpp
  src/badguy/mriceblock.hpp
  src/badguy/smartball.hpp
  src/badguy/smartblock.hpp
  src/badguy/snowball.hpp
Labels: involves:editor, type:patch, category:code
