Repository SuperTux/supertux, pull requests merged in 2023-08, with the labels that each got.

#2510 Fixes and updates for Ubuntu Touch port
  .github/workflows/ubuntu-touch.yml
  clickable.json
  clickable.yaml
  mk/clickable/BROKEN-build-with-glbinding.json
  mk/clickable/build-with-glew.json
  mk/clickable/clickable-glbinding.yaml
  mk/clickable/clickable-glew.yaml
  mk/clickable/supertux2.apparmor
Labels: category:tests, type:bugfix, os:ubuntu-touch

#2513 Pause target timer via scripting
  data/scripts/default.nut
  src/scripting/level.cpp
  src/scripting/level.hpp
  src/scripting/wrapper.cpp
  src/supertux/game_session.cpp
  src/supertux/game_session.hpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2558 Add a flip-action option for sprite actions
  data/images/creatures/crystallo/rcrystallo.sprite
  data/images/creatures/dart/dart.sprite
  data/images/creatures/darttrap/darttrap.sprite
  data/images/objects/ispy/i-hiding-up.png
  data/images/objects/ispy/i-idle-up.png
  data/images/objects/ispy/i-shaking-up.png
  data/images/objects/ispy/i-shaking2-up.png
  data/images/objects/ispy/i-shaking3-up.png
  data/images/objects/ispy/i-showing1-up.png
  data/images/objects/ispy/i-showing2-up.png
  data/images/objects/ispy/i-showing3-up.png
  data/images/objects/ispy/ispy.sprite
  src/badguy/badguy.hpp
  src/badguy/dart.cpp
  src/badguy/dart.hpp
  src/badguy/darttrap.cpp
  src/badguy/darttrap.hpp
  src/badguy/rcrystallo.cpp
  src/scripting/badguy.cpp
  src/sprite/sprite_data.cpp
Labels: type:feature, category:code

#2564 Create objects from scripting
  src/scripting/sector.cpp
  src/scripting/sector.hpp
  src/scripting/wrapper.cpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2578 Add options menu to editor menu
  src/supertux/menu/editor_menu.cpp
  src/supertux/menu/editor_menu.hpp
Labels: involves:editor, type:feature, category:code, status:needs-review

#2580 Add `Tux.set_velocity()` to scripting API.
  src/scripting/player.cpp
  src/scripting/player.hpp
  src/scripting/wrapper.cpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2576 Crystallo <-> Roof Crystallo on levelflip
  data/images/creatures/crystallo/crystallo.sprite
  data/images/creatures/crystallo/rcrystallo.sprite
  data/images/creatures/crystallo/scrystallo.sprite
  src/badguy/crystallo.cpp
  src/badguy/crystallo.hpp
  src/badguy/rcrystallo.cpp
  src/badguy/rcrystallo.hpp
  src/badguy/scrystallo.cpp
  src/badguy/scrystallo.hpp
  src/supertux/physic.hpp
Labels: involves:functionality, category:code, status:needs-review

#2589 Properly initialise harmless fish
  src/badguy/fish_harmless.cpp
Labels: category:code, type:bugfix

#2590 Fix missing (or rather, not loading) editor sprite actions
  src/badguy/badguy.cpp
  src/badguy/sspiky.cpp
  src/badguy/sspiky.hpp
Labels: involves:editor, category:code, status:needs-review, type:bugfix

#2584 Fix corrupted crusher not spawning roots when hit.top
  data/images/creatures/crusher/corrupted/krosh_corrupt.sprite
  data/images/creatures/crusher/corrupted/krosh_eye_glow.sprite
  data/images/creatures/crusher/corrupted/krush_corrupt.sprite
  data/images/creatures/crusher/corrupted/krush_eye_glow.sprite
  data/images/creatures/crusher/roots/crusher_root.sprite
  data/images/creatures/crusher/roots/crusher_root_side.sprite
  src/badguy/crusher.cpp
  src/badguy/crusher.hpp
Labels: category:code, status:needs-review, type:bugfix

#2591 Fix memory leaks and code quality in autotile code
  src/supertux/autotile.cpp
  src/supertux/autotile.hpp
  src/supertux/autotile_parser.cpp
  src/supertux/autotile_parser.hpp
  src/supertux/tile_set.cpp
  src/supertux/tile_set.hpp
  src/supertux/tile_set_parser.cpp
Labels: category:code, status:needs-review

#2588 Re-disable gravity for Sleeping Crystallo, fix missing sprite actions
  data/images/creatures/crystallo/crystallo.sprite
  src/badguy/rcrystallo.cpp
  src/badguy/scrystallo.cpp
Labels: involves:functionality, category:code, status:needs-review, involves:physics, type:bugfix

#2586 Make thrown bombs explode on impact
  src/badguy/bomb.cpp
  src/badguy/goldbomb.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review

#2609 Extend sub-pixel rendering support
  src/control/mobile_controller.cpp
  src/editor/overlay_widget.cpp
  src/editor/toolbox_widget.cpp
  src/gui/dialog.cpp
  src/gui/notification.cpp
  src/interface/control_scrollbar.cpp
  src/interface/control_scrollbar.hpp
  src/math/rect.cpp
  src/math/rect.hpp
  src/math/rectf.cpp
  src/math/rectf.hpp
  src/object/background.cpp
  src/object/camera.cpp
  src/object/camera.hpp
  src/object/display_effect.cpp
  src/object/floating_image.cpp
  src/object/gradient.cpp
  src/object/level_time.cpp
  src/object/rain_particle_system.cpp
  src/object/text_object.cpp
  src/object/textscroller.cpp
  src/object/thunderstorm.cpp
  src/object/vertical_stripes.cpp
  src/scripting/camera.cpp
  src/scripting/camera.hpp
  src/scripting/wrapper.cpp
  src/supertux/console.cpp
  src/supertux/fadetoblack.cpp
  src/supertux/game_session.cpp
  src/supertux/info_box.cpp
  src/supertux/levelintro.cpp
  src/supertux/player_status_hud.cpp
  src/supertux/screen_manager.cpp
  src/supertux/statistics.cpp
  src/supertux/textscroller_screen.cpp
  src/supertux/title_screen.cpp
  src/trigger/secretarea_trigger.cpp
  src/video/drawing_context.cpp
  src/video/drawing_context.hpp
  src/video/sdl/sdl_painter.cpp
  src/worldmap/world_select.cpp
  src/worldmap/worldmap_sector.cpp
Labels: category:code, status:needs-review, type:bugfix

#2613 Tuxs action updates regardless of whether Tux is being drawn.
  src/object/player.cpp
Labels: category:code, involves:scripting, status:needs-review, type:bugfix

#2607 Fix camera zooming in "manual" mode
  src/math/anchor_point.cpp
  src/math/anchor_point.hpp
  src/object/camera.cpp
  src/object/camera.hpp
  src/scripting/camera.cpp
  src/scripting/camera.hpp
  src/scripting/wrapper.cpp
Labels: category:code, status:needs-review, type:bugfix
