Repository SuperTux/supertux, pull requests merged in 2023-07, with the labels that each got.

#2497 Allow dispensing objects, dispenser object customization
  src/badguy/badguy.cpp
  src/badguy/badguy.hpp
  src/badguy/dispenser.cpp
  src/badguy/dispenser.hpp
  src/badguy/goldbomb.cpp
  src/editor/layers_widget.cpp
  src/editor/object_menu.cpp
  src/editor/object_menu.hpp
  src/editor/object_option.cpp
  src/editor/object_option.hpp
  src/editor/object_settings.cpp
  src/editor/object_settings.hpp
  src/editor/overlay_widget.cpp
  src/gui/item_badguy_select.cpp
  src/gui/item_badguy_select.hpp
  src/gui/menu.cpp
  src/gui/menu.hpp
  src/gui/menu_badguy_select.cpp
  src/gui/menu_list.cpp
  src/gui/menu_list.hpp
  src/gui/menu_object_select.cpp
  src/gui/menu_object_select.hpp
  src/object/bonus_block.cpp
  src/object/coin.cpp
  src/object/coin.hpp
  src/object/coin_explode.cpp
  src/object/coin_explode.hpp
  src/object/coin_rain.cpp
  src/object/coin_rain.hpp
  src/object/explosion.hpp
  src/supertux/game_object.cpp
  src/supertux/game_object_factory.cpp
  src/supertux/game_object_factory.hpp
  src/supertux/moving_object.cpp
  src/supertux/moving_object.hpp
  src/supertux/object_factory.cpp
  src/supertux/object_factory.hpp
  tests/object_option_test.cpp
Labels: type:feature, category:code, status:needs-review

#2495 New Badguy: Dive mine
  data/images/creatures/dive_mine/dive_mine.sprite
  data/images/creatures/dive_mine/left-0.png
  data/images/creatures/dive_mine/left-1.png
  data/images/creatures/dive_mine/left-10.png
  data/images/creatures/dive_mine/left-11.png
  data/images/creatures/dive_mine/left-2.png
  data/images/creatures/dive_mine/left-3.png
  data/images/creatures/dive_mine/left-4.png
  data/images/creatures/dive_mine/left-5.png
  data/images/creatures/dive_mine/left-6.png
  data/images/creatures/dive_mine/left-7.png
  data/images/creatures/dive_mine/left-8.png
  data/images/creatures/dive_mine/left-9.png
  data/images/creatures/dive_mine/ticking-0.png
  data/images/creatures/dive_mine/ticking-1.png
  data/images/creatures/dive_mine/ticking-2.png
  data/images/creatures/dive_mine/ticking-3.png
  data/images/creatures/dive_mine/ticking-4.png
  data/images/creatures/dive_mine/ticking-5.png
  data/images/creatures/dive_mine/ticking-6.png
  data/images/creatures/dive_mine/ticking-7.png
  data/images/creatures/dive_mine/ticking-8.png
  data/images/creatures/dive_mine/ticking-9.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow-0.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow-1.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow-2.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow-3.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow-4.png
  data/images/creatures/dive_mine/ticking_glow/ticking_glow.sprite
  data/images/engine/editor/objects.stoi
  src/badguy/dive_mine.cpp
  src/badguy/dive_mine.hpp
  src/supertux/game_object_factory.cpp
Labels: status:in-progress, type:feature, category:code, category:design

#2479 New Tux run animation
  data/images/creatures/tux/big/run-0.png
  data/images/creatures/tux/big/run-1.png
  data/images/creatures/tux/big/run-2.png
  data/images/creatures/tux/big/run-3.png
  data/images/creatures/tux/big/run-4.png
  data/images/creatures/tux/big/run-5.png
  data/images/creatures/tux/big/run-6.png
  data/images/creatures/tux/big/run-7.png
  data/images/creatures/tux/big/run_transition-0.png
  data/images/creatures/tux/big/walk_transition-0.png
  data/images/creatures/tux/small/run-0.png
  data/images/creatures/tux/small/run-1.png
  data/images/creatures/tux/small/run-2.png
  data/images/creatures/tux/small/run-3.png
  data/images/creatures/tux/small/run-4.png
  data/images/creatures/tux/small/run-5.png
  data/images/creatures/tux/small/run-6.png
  data/images/creatures/tux/small/run-7.png
  data/images/creatures/tux/small/run_transition-0.png
  data/images/creatures/tux/small/walk_transition-0.png
  data/images/creatures/tux/tux.sprite
  src/object/player.cpp
Labels: category:design, status:needs-review

#2534 Rublight sparkle is played when someone steps on it.
  data/images/objects/rublight/rublight.sprite
  src/object/rublight.cpp
Labels: type:feature, category:code

#2530 Unstable tile now refuses to respawn when tux is occupying original position
  src/object/unstable_tile.cpp
Labels: category:code, status:needs-review, type:bugfix

#2544 Abstract PhysFS enumerate into PhysfsUtil
  src/addon/addon_manager.cpp
  src/gui/menu_filesystem.cpp
  src/physfs/physfs_file_system.cpp
  src/physfs/util.cpp
  src/physfs/util.hpp
  src/supertux/levelset.cpp
  src/supertux/menu/contrib_menu.cpp
  src/supertux/menu/editor_levelset_select_menu.cpp
  src/supertux/menu/profile_menu.cpp
  src/video/bitmap_font.cpp
Labels: category:code, status:needs-review

#2549 Fix oklab colour picker rendering when using SDL
  src/video/sdl/sdl_painter.cpp
Labels: involves:editor, category:code, status:needs-review, type:bugfix

#2546 Ability to set bonus block coin sprite for coin, coin rain and coin explosion
  src/object/bonus_block.cpp
  src/object/bonus_block.hpp
  src/object/coin.cpp
  src/object/coin.hpp
  src/object/coin_explode.cpp
  src/object/coin_explode.hpp
  src/object/coin_rain.cpp
  src/object/coin_rain.hpp
Labels: type:feature, category:code

#2535 Earth powerup stone form breaks bricks below without stopping
  src/object/brick.cpp
  src/object/player.cpp
Labels: involves:functionality, type:feature, category:code

#2537 Ability to open debug menu in editor
  src/editor/editor.cpp
  src/supertux/menu/debug_menu.cpp
  src/supertux/menu/debug_menu.hpp
Labels: involves:editor, type:feature, category:code, status:needs-review

#2547 Fix worldmap sector spawnpoint issues, testing from worldmap spawnpoints
  src/editor/editor.cpp
  src/supertux/game_manager.cpp
  src/supertux/game_manager.hpp
  src/supertux/game_session.cpp
  src/worldmap/spawn_point.cpp
  src/worldmap/tux.cpp
  src/worldmap/tux.hpp
  src/worldmap/world_select.cpp
  src/worldmap/worldmap.cpp
  src/worldmap/worldmap.hpp
  src/worldmap/worldmap_sector.cpp
  src/worldmap/worldmap_sector.hpp
  src/worldmap/worldmap_state.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review, type:bugfix

#2551 Fix sprite fallback issues
  src/object/moving_sprite.cpp
  src/sprite/sprite_data.cpp
  src/sprite/sprite_data.hpp
  src/sprite/sprite_manager.cpp
  src/sprite/sprite_manager.hpp
  src/video/texture_manager.cpp
  src/video/texture_manager.hpp
Labels: category:code, status:needs-review, type:bugfix

#2553 Code style changes to satisfy CppCheck
  src/audio/stream_sound_source.cpp
  src/badguy/crusher.cpp
Labels: category:code, status:needs-review

#2555 Allow placing tiles in edges with rect fill tool
  src/editor/overlay_widget.cpp
Labels: involves:editor, category:code, status:needs-review, type:bugfix

#2552 Prevent propagating movement to statics like bonus blocks
  src/collision/collision_object.cpp
Labels: category:code, status:needs-review, involves:physics, type:bugfix

#2562 Fix buttjump hitbox to not include actual player
  src/object/player.cpp
Labels: category:code, type:bugfix

#2554 Improvements to Dart and DartTrap
  data/images/creatures/dart/dart.sprite
  data/images/creatures/dart/flying-down.png
  data/images/creatures/dart/flying-left.png
  data/images/creatures/darttrap/darttrap.sprite
  data/images/creatures/darttrap/down-1.png
  data/images/creatures/darttrap/down-2.png
  data/images/creatures/darttrap/down-3.png
  data/images/creatures/darttrap/down-4.png
  data/images/creatures/darttrap/down-idle.png
  data/images/creatures/darttrap/left-1.png
  data/images/creatures/darttrap/left-2.png
  data/images/creatures/darttrap/left-3.png
  data/images/creatures/darttrap/left-4.png
  data/images/creatures/darttrap/left-idle.png
  data/images/engine/editor/objects.stoi
  src/badguy/dart.cpp
  src/badguy/dart.hpp
  src/badguy/darttrap.cpp
  src/badguy/darttrap.hpp
Labels: involves:functionality, type:feature, category:code, status:needs-review

#2556 Fix editor not updating direction of badguys, conveyor belts and bumpers
  src/badguy/badguy.cpp
  src/object/bumper.cpp
  src/object/bumper.hpp
  src/object/conveyor_belt.cpp
  src/object/fallblock.cpp
  src/object/fallblock.hpp
Labels: involves:editor, category:code, status:needs-review, type:bugfix
