Repository SuperTux/supertux, pull requests merged in 2024-10, with the labels that each got.

#2987 Fix windows crash viewer
  mk/cmake/SuperTux/BuildInstall.cmake
  src/supertux/error_handler.cpp
  src/supertux/error_handler.hpp
Labels: os:windows, type:patch, status:in-progress, category:code

#3068 Fix slidejumping as big tux
  src/object/player.cpp
Labels: category:code, status:needs-review, type:bugfix

#2928 Reloading resources from "Debug" menu
  src/object/moving_sprite.cpp
  src/sprite/sprite.hpp
  src/sprite/sprite_data.cpp
  src/sprite/sprite_data.hpp
  src/sprite/sprite_manager.cpp
  src/sprite/sprite_manager.hpp
  src/supertux/menu/debug_menu.cpp
  src/supertux/resources.cpp
  src/supertux/resources.hpp
  src/supertux/tile_manager.cpp
  src/supertux/tile_manager.hpp
  src/supertux/tile_set.cpp
  src/supertux/tile_set.hpp
  src/video/gl/gl_texture.cpp
  src/video/gl/gl_texture.hpp
  src/video/null/null_texture.cpp
  src/video/null/null_texture.hpp
  src/video/sdl/sdl_texture.cpp
  src/video/sdl/sdl_texture.hpp
  src/video/sdl_surface_ptr.hpp
  src/video/texture.cpp
  src/video/texture.hpp
  src/video/texture_manager.cpp
  src/video/texture_manager.hpp
  src/video/ttf_surface_manager.cpp
  src/video/ttf_surface_manager.hpp
Labels: type:feature, category:code, status:needs-review

#3082 Editor: Support multiple autotilesets per tile
  data/images/autotiles.satc
  src/editor/editor.cpp
  src/editor/editor.hpp
  src/editor/overlay_widget.cpp
  src/editor/overlay_widget.hpp
  src/editor/toolbox_widget.cpp
  src/object/tilemap.cpp
  src/object/tilemap.hpp
  src/supertux/autotile.hpp
  src/supertux/tile_set.cpp
  src/supertux/tile_set.hpp
Labels: involves:editor, involves:functionality, type:feature, category:code, status:needs-review

#3085 `GameObject` change undo/redo refactor to track different options
  src/editor/layers_widget.cpp
  src/editor/layers_widget.hpp
  src/editor/object_option.cpp
  src/editor/object_option.hpp
  src/editor/object_settings.cpp
  src/editor/object_settings.hpp
  src/object/tilemap.cpp
  src/object/tilemap.hpp
  src/supertux/game_object.cpp
  src/supertux/game_object.hpp
  src/supertux/game_object_change.cpp
  src/supertux/game_object_change.hpp
  src/supertux/game_object_manager.cpp
  src/supertux/game_object_manager.hpp
  src/util/reader_mapping.cpp
  src/util/reader_mapping.hpp
  src/util/uid.hpp
  src/util/writer.cpp
  src/util/writer.hpp
  src/video/color.cpp
  src/video/color.hpp
Labels: involves:editor, type:patch, category:code, status:needs-review

#2376 Disable the update checker by default and add option to disable networking
  src/addon/addon_manager.cpp
  src/addon/downloader.cpp
  src/gui/menu_manager.cpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/main.cpp
  src/supertux/menu/addon_menu.cpp
  src/supertux/menu/addon_preview_menu.cpp
  src/supertux/menu/main_menu.cpp
  src/supertux/menu/options_menu.cpp
  src/supertux/menu/options_menu.hpp
Labels: category:code, status:needs-work
