Repository SuperTux/supertux, pull requests merged in 2024-05, with the labels that each got.

#2781 Save VSync setting
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/menu/options_menu.cpp
  src/video/gl/gl_video_system.cpp
Labels: category:code, status:needs-review, type:bugfix

#2919 Use code font for console and script editor
  data/fonts/SOURCECODEPRO_LICENSE.md
  data/fonts/SourceCodePro-Medium.ttf
  src/supertux/resources.cpp
Labels: status:needs-discussion

#2934 Add GitHub issue forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/crash.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: category:meta, status:needs-review

#2925 Fix badguys not climbing certain slopes
  src/badguy/walking_badguy.cpp
Labels: category:code, status:needs-review, type:bugfix

#2908 Handle errors with a stacktrace dialog
  src/supertux/error_handler.cpp
  src/supertux/error_handler.hpp
  src/supertux/main.cpp
  src/util/file_system.cpp
  src/util/file_system.hpp
Labels: type:patch, category:code, status:needs-review

#2820 New Tarantula behavior + Spidermite Variant
  data/images/creatures/spidermite/burning-0.png
  data/images/creatures/spidermite/burning-1.png
  data/images/creatures/spidermite/burning-2.png
  data/images/creatures/spidermite/burning-3.png
  data/images/creatures/spidermite/burning-4.png
  data/images/creatures/spidermite/burning-5.png
  data/images/creatures/spidermite/burning-6.png
  data/images/creatures/spidermite/burning-7.png
  data/images/creatures/spidermite/spidermite-0.png
  data/images/creatures/spidermite/spidermite-1.png
  data/images/creatures/spidermite/spidermite-2.png
  data/images/creatures/spidermite/spidermite-3.png
  data/images/creatures/spidermite/spidermite-4.png
  data/images/creatures/spidermite/spidermite-5.png
  data/images/creatures/spidermite/spidermite-6.png
  data/images/creatures/spidermite/spidermite-7.png
  data/images/creatures/spidermite/spidermite-8.png
  data/images/creatures/spidermite/spidermite-9.png
  data/images/creatures/spidermite/spidermite-squish.png
  data/images/creatures/spidermite/spidermite.sprite
  data/images/creatures/spidermite/spidermite1.png
  data/images/creatures/spidermite/spidermite2.png
  data/images/creatures/spidermite/spidermite3.png
  data/images/creatures/spidermite/spidermite4.png
  data/images/creatures/spidermite/spidermite5.png
  data/images/creatures/spidermite/spidermite6.png
  data/images/creatures/spidermite/squished.png
  data/images/creatures/tarantula/silk.png
  data/images/creatures/tarantula/squished.png
  data/images/creatures/tarantula/tarantula-0.png
  data/images/creatures/tarantula/tarantula-1.png
  data/images/creatures/tarantula/tarantula-2.png
  data/images/creatures/tarantula/tarantula-3.png
  data/images/creatures/tarantula/tarantula-4.png
  data/images/creatures/tarantula/tarantula-5.png
  data/images/creatures/tarantula/tarantula-6.png
  data/images/creatures/tarantula/tarantula-7.png
  data/images/creatures/tarantula/tarantula-8.png
  data/images/creatures/tarantula/tarantula-9.png
  data/images/creatures/tarantula/tarantula.sprite
  data/images/engine/editor/objects.stoi
  src/badguy/spidermite.cpp
  src/badguy/spidermite.hpp
  src/badguy/tarantula.cpp
  src/badguy/tarantula.hpp
  src/supertux/game_object_factory.cpp
Labels: type:feature, category:code, category:design, status:needs-review

#2940 Root will not hurt while hatching
  src/badguy/root.cpp
Labels: involves:functionality, category:code, status:needs-review

#2884 Editor: Adding layers from layers widget
  data/images/engine/editor/add.png
  data/images/engine/editor/objects.stoi
  src/editor/editor.cpp
  src/editor/editor.hpp
  src/editor/layers_widget.cpp
  src/editor/layers_widget.hpp
  src/editor/object_info.cpp
  src/editor/object_info.hpp
  src/editor/overlay_widget.cpp
  src/editor/tilebox.cpp
  src/editor/tilebox.hpp
  src/editor/toolbox_widget.cpp
  src/editor/toolbox_widget.hpp
Labels: involves:editor, type:feature, category:code, category:design, status:needs-review

#2949 Remaster credits.ogg
  data/music/misc/credits.ogg
Labels: type:patch, status:needs-review
