Repository SuperTux/supertux, pull requests merged in 2024-06, with the labels that each got.

#2948 Igel Improvements
  src/badguy/igel.cpp
  src/badguy/igel.hpp
Labels: type:patch, involves:functionality, category:code, status:needs-review

#2955 Corrupted version of Swimming Fish & Chasing Fish
  data/images/creatures/fish/forest/corrupted/chase_brown-0.png
  data/images/creatures/fish/forest/corrupted/chase_brown-1.png
  data/images/creatures/fish/forest/corrupted/chase_brown-2.png
  data/images/creatures/fish/forest/corrupted/chase_brown-3.png
  data/images/creatures/fish/forest/corrupted/chase_brown-4.png
  data/images/creatures/fish/forest/corrupted/chase_brown-5.png
  data/images/creatures/fish/forest/corrupted/corrupted_bluefish.sprite
  data/images/creatures/fish/forest/corrupted/corrupted_brownfish.sprite
  data/images/creatures/fish/forest/corrupted/notice_brown-0.png
  data/images/creatures/fish/forest/corrupted/notice_brown-1.png
  data/images/creatures/fish/forest/corrupted/notice_brown-2.png
  data/images/creatures/fish/forest/corrupted/notice_brown-3.png
  data/images/creatures/fish/forest/corrupted/swim_blue-0.png
  data/images/creatures/fish/forest/corrupted/swim_blue-1.png
  data/images/creatures/fish/forest/corrupted/swim_blue-2.png
  data/images/creatures/fish/forest/corrupted/swim_blue-3.png
  data/images/creatures/fish/forest/corrupted/swim_blue-4.png
  data/images/creatures/fish/forest/corrupted/swim_blue-5.png
  data/images/creatures/fish/forest/corrupted/swim_blue-6.png
  data/images/creatures/fish/forest/corrupted/swim_blue-7.png
  data/images/creatures/fish/forest/corrupted/swim_brown-0.png
  data/images/creatures/fish/forest/corrupted/swim_brown-1.png
  data/images/creatures/fish/forest/corrupted/swim_brown-2.png
  data/images/creatures/fish/forest/corrupted/swim_brown-3.png
  data/images/creatures/fish/forest/corrupted/swim_brown-4.png
  data/images/creatures/fish/forest/corrupted/swim_brown-5.png
  data/images/creatures/fish/forest/corrupted/swim_brown-6.png
  data/images/creatures/fish/forest/corrupted/swim_brown-7.png
  src/badguy/fish_chasing.cpp
  src/badguy/fish_swimming.cpp
  src/badguy/fish_swimming.hpp
Labels: category:code, category:design, status:needs-review

#2957 Reset spawn fade type when using Level.spawn()
  src/supertux/game_session.cpp
Labels: category:code, involves:scripting, type:bugfix

#2965 Save worldmap music in worldmap state
  src/worldmap/worldmap_state.cpp
Labels: type:feature, category:code, status:needs-review

#2963 Generate builds with `RelWithDebInfo` instead of `Release`
  .github/workflows/bsd.yml
  .github/workflows/gnulinux.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu-touch.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: type:patch, status:needs-review, category:tests

#2970 Only call glGetUniformLocation/glGetAttribLocation once
  src/video/gl/gl33core_context.cpp
  src/video/gl/gl_program.cpp
  src/video/gl/gl_program.hpp
  src/video/gl/gl_vertex_arrays.cpp
Labels: type:patch, involves:performance, category:code, status:needs-review

#2846 Incorporate certain object dynamics
  src/badguy/badguy.cpp
  src/badguy/badguy.hpp
  src/badguy/crusher.cpp
  src/badguy/darttrap.cpp
  src/badguy/darttrap.hpp
  src/badguy/dive_mine.cpp
  src/badguy/fish_jumping.cpp
  src/badguy/fish_swimming.cpp
  src/badguy/rcrystallo.cpp
  src/badguy/stalactite.cpp
  src/badguy/stalactite.hpp
  src/badguy/viciousivy.cpp
  src/badguy/walkingleaf.cpp
  src/badguy/yeti_stalactite.cpp
  src/object/bullet.cpp
  src/object/bumper.cpp
  src/object/bumper.hpp
  src/object/fallblock.cpp
  src/object/fallblock.hpp
  src/object/ispy.cpp
  src/object/ispy.hpp
  src/object/platform.cpp
  src/object/platform.hpp
  src/object/player.cpp
  src/object/pushbutton.cpp
  src/object/pushbutton.hpp
  src/object/rock.cpp
  src/object/rock.hpp
  src/object/shard.cpp
  src/object/shard.hpp
  src/object/sticky_object.cpp
  src/object/sticky_object.hpp
  src/object/trampoline.cpp
  src/object/trampoline.hpp
  src/trigger/switch.cpp
  src/trigger/switch.hpp
  src/trigger/trigger_base.cpp
  src/trigger/trigger_base.hpp
Labels: involves:functionality, type:feature, category:code, status:needs-review, involves:physics

#2985 ST OST - Two forest songs
  data/AUTHORS
  data/music/forest/forest_midday.music
  data/music/forest/forest_midday.ogg
  data/music/forest/forest_midday_alt.music
  data/music/forest/forest_midday_alt.ogg
Labels: status:needs-review
