Repository SuperTux/supertux, pull requests merged in 2024-01, with the labels that each got.

#2575 New death sound
  data/sounds/kill.wav
Labels: category:design, status:needs-review

#2688 Refactor AmbientSound
  data/images/engine/editor/music.png
  data/images/engine/editor/objects.stoi
  data/images/engine/editor/sound.png
  src/audio/dummy_sound_source.cpp
  src/audio/openal_sound_source.cpp
  src/audio/openal_sound_source.hpp
  src/audio/sound_source.hpp
  src/object/ambient_sound.cpp
  src/object/ambient_sound.hpp
  src/object/sound_object.cpp
  src/object/sound_object.hpp
  src/scripting/sound_object.cpp
  src/scripting/sound_object.hpp
  src/scripting/wrapper.cpp
  src/scripting/wrapper.hpp
  src/scripting/wrapper.interface.hpp
  src/supertux/game_object_factory.cpp
Labels: involves:functionality, status:in-progress, type:feature, category:code, involves:scripting

#2727 Support for `region` sprite action frames
  src/sprite/sprite_data.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review

#2722 Instantiable `Text` and `TextArray` objects
  src/object/text_array_object.cpp
  src/object/text_array_object.hpp
  src/object/text_object.cpp
  src/object/text_object.hpp
  src/scripting/text_array_object.cpp
  src/scripting/text_array_object.hpp
  src/scripting/text_object.cpp
  src/scripting/text_object.hpp
  src/scripting/wrapper.cpp
  src/scripting/wrapper.hpp
  src/scripting/wrapper.interface.hpp
  src/supertux/game_object_factory.cpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
  src/trigger/text_area.cpp
Labels: type:feature, category:code, involves:scripting, status:needs-review

#2734 Rename `Rectf::contains(const Rectf&)` to `Rectf::overlaps(const Rectf&)`
  src/badguy/crusher.cpp
  src/collision/collision.cpp
  src/collision/collision.hpp
  src/collision/collision_system.cpp
  src/editor/overlay_widget.cpp
  src/math/rectf.hpp
  src/object/ambient_sound.cpp
  src/object/coin.cpp
  src/object/custom_particle_system.cpp
  src/object/particlesystem_interactive.cpp
  src/object/player.cpp
  src/video/sdl/sdl_painter.cpp
  tests/collision_test.cpp
  tests/rectf_test.cpp
Labels: category:code, status:needs-review

#2719 Cloning paths in editor, fix various undo/redo issues
  src/editor/overlay_widget.cpp
  src/object/camera.cpp
  src/object/camera.hpp
  src/object/coin.cpp
  src/object/coin.hpp
  src/object/path_gameobject.cpp
  src/object/path_gameobject.hpp
  src/object/path_object.cpp
  src/object/path_object.hpp
  src/object/platform.cpp
  src/object/tilemap.cpp
  src/object/tilemap.hpp
  src/supertux/game_object_manager.cpp
  src/supertux/sector.cpp
Labels: involves:editor, category:code, status:needs-review

#2749 Improve chasing fish
  src/badguy/dive_mine.cpp
  src/badguy/dive_mine.hpp
  src/badguy/fish_chasing.cpp
  src/badguy/fish_chasing.hpp
Labels: category:code, status:needs-review

#2745 Emscripten link flag adjustments
  CMakeLists.txt
Labels: type:patch, status:needs-review
