Repository SuperTux/supertux, pull requests merged in 2024-07, with the labels that each got.

#2894 Tileset additions + minor fixes
  data/images/autotiles.satc
  data/images/tiles.strf
  data/images/tiles/background/corrupt_seaweed-0.png
  data/images/tiles/background/seaweed-0.png
  data/images/tiles/blocks/block4.png
  data/images/tiles/blocks/block_horiz.png
  data/images/tiles/blocks/block_vert.png
  data/images/tiles/blocks/block_wood.png
  data/images/tiles/crystalcave/crystal_1x1.png
  data/images/tiles/crystalcave/crystal_1x1_extra.png
  data/images/tiles/crystalcave/crystal_1x1_extra2.png
  data/images/tiles/crystalcave/crystal_2x2.png
  data/images/tiles/crystalcave/crystal_variants.png
  data/images/tiles/crystalcave/deprecated/crystal_2x2.png
  data/images/tiles/forest/pogonia.png
  data/images/tiles/forest/spikevine.png
  data/images/tiles/goal/goal1-1.png
  data/images/tiles/goal/goal1-2.png
  data/images/tiles/goal/goal1-3.png
  data/images/tiles/goal/goal1-4.png
  data/images/tiles/goal/goal1-5.png
  data/images/tiles/retro/retro_castle.png
  data/images/tiles/retro/retro_cave.png
  data/images/tiles/retro/retro_snow.png
  data/images/tiles/snow/icechunk.png
  data/images/tiles/snow/underground/background.png
Labels: type:patch, category:design, status:needs-review

#2827 Camera: Customizable peek multiplier
  src/object/camera.cpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/menu/options_menu.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review

#2997 Add an option to hide wind particles + set fancy as default
  src/object/wind.cpp
  src/object/wind.hpp
Labels: category:code, status:needs-review

#2990 Always keep dispensers active
  src/badguy/badguy.cpp
  src/badguy/badguy.hpp
  src/badguy/dispenser.hpp
Labels: status:needs-review, type:bugfix

#3000 Add an option for the thunderstorm flash
  src/object/thunderstorm.cpp
  src/supertux/gameconfig.cpp
  src/supertux/gameconfig.hpp
  src/supertux/menu/options_menu.cpp
  src/supertux/menu/options_menu.hpp
Labels: status:needs-discussion, category:code

#3015 Add "Show Tile Ids In Editor" to debug menu.
  src/editor/tilebox.cpp
  src/supertux/debug.cpp
  src/supertux/debug.hpp
  src/supertux/menu/debug_menu.cpp
Labels: involves:editor, type:feature, category:code, status:needs-review

#2954 Scale parallax layers perspectively-correctly
  src/object/background.cpp
  src/object/tilemap.cpp
  src/video/drawing_context.cpp
  src/video/drawing_context.hpp
Labels: type:patch, category:code, status:needs-review

#3027 Do not show debug box for solid tiles in non-solid tilemaps
  src/object/tilemap.cpp
Labels: type:patch, category:code, status:needs-review

#2748 Background ".sprite" support
  src/object/background.cpp
  src/object/background.hpp
  src/sprite/sprite.cpp
  src/sprite/sprite.hpp
Labels: involves:functionality, type:feature, category:code, involves:scripting, status:needs-review
