Repository SuperTux/supertux, pull requests merged in 2024-02, with the labels that each got.

#2756 Improve snow particle customizability and code style
  src/object/snow_particle_system.cpp
  src/object/snow_particle_system.hpp
Labels: involves:editor, involves:functionality, type:feature, category:code, status:needs-review

#2763 Rotate Tux sprite if sliding on slope
  src/object/player.cpp
Labels: involves:functionality, type:feature, category:code

#2769 Update HTML template page
  mk/emscripten/template.html.in
Labels: type:patch, category:code

#2757 Remove `CameraConfig`
  src/object/camera.cpp
  src/object/camera.hpp
  src/scripting/camera.cpp
  src/scripting/camera.hpp
  src/scripting/wrapper.cpp
Labels: involves:functionality, status:needs-discussion, category:code, status:needs-review

#2782 ST OST - Some songs i made for the music overhaul
  data/AUTHORS
  data/music/antarctic/night.music
  data/music/antarctic/night.ogg
  data/music/antarctic/skylevel.music
  data/music/antarctic/skylevel.ogg
  data/music/antarctic/sunset.music
  data/music/antarctic/sunset.ogg
  data/music/antarctic/worldmap_ice.music
  data/music/antarctic/worldmap_ice.ogg
Labels: status:needs-review

#2788 Fix crusher not changing sprites and only choosing small ice crusher
  src/badguy/crusher.cpp
Labels: type:patch, category:code, status:needs-review

#2786 Fix some enemies not going down slopes
  src/badguy/captainsnowball.cpp
  src/badguy/crystallo.cpp
  src/badguy/goldbomb.cpp
  src/badguy/haywire.cpp
  src/badguy/igel.cpp
  src/badguy/livefire.cpp
  src/badguy/mrbomb.cpp
  src/badguy/mriceblock.cpp
  src/badguy/mrtree.cpp
  src/badguy/rcrystallo.cpp
  src/badguy/scrystallo.cpp
  src/badguy/short_fuse.cpp
  src/badguy/smartball.cpp
  src/badguy/smartblock.cpp
  src/badguy/snail.cpp
  src/badguy/spiky.cpp
  src/badguy/sspiky.cpp
  src/badguy/stumpy.cpp
  src/badguy/walking_badguy.cpp
  src/badguy/walking_badguy.hpp
  src/badguy/walkingleaf.cpp
Labels: involves:functionality, category:code, status:needs-review

#2801 Fix fish dissapear when going to the bottom of the sector in water
  src/badguy/fish_swimming.cpp
  src/badguy/fish_swimming.hpp
Labels: involves:functionality, category:code, status:needs-review, type:bugfix

#2795 Improve Tux' sliding behavior
  src/object/player.cpp
  src/object/player.hpp
  src/sprite/sprite.cpp
  src/sprite/sprite.hpp
Labels: category:code, status:needs-review

#2778 Fix outdated file paths in custom particles code
  src/object/custom_particle_system.cpp
  src/object/custom_particle_system.hpp
  src/object/custom_particle_system_file.hpp
Labels: category:code, status:needs-review, type:bugfix
