Repository SuperTux/supertux, pull requests merged in 2024-08, with the labels that each got.

#3002 Merge Bomb with MrBomb
  src/badguy/bomb.cpp
  src/badguy/bomb.hpp
  src/badguy/goldbomb.cpp
  src/badguy/goldbomb.hpp
  src/badguy/mrbomb.cpp
  src/badguy/mrbomb.hpp
  src/object/block.cpp
Labels: type:patch, involves:functionality, category:code, status:needs-review

#3032 `Screen`: Virtual methods for SDL and window resize events
  src/editor/button_widget.cpp
  src/editor/button_widget.hpp
  src/editor/editor.cpp
  src/editor/editor.hpp
  src/editor/layers_widget.cpp
  src/editor/layers_widget.hpp
  src/editor/overlay_widget.cpp
  src/editor/overlay_widget.hpp
  src/editor/particle_editor.hpp
  src/editor/tilebox.cpp
  src/editor/tilebox.hpp
  src/editor/toolbox_widget.cpp
  src/editor/toolbox_widget.hpp
  src/editor/widget.cpp
  src/editor/widget.hpp
  src/supertux/menu/options_menu.cpp
  src/supertux/screen.hpp
  src/supertux/screen_manager.cpp
  src/supertux/screen_manager.hpp
Labels: category:code, status:needs-review, type:bugfix

#2662 Revenge in Redmond Update
  data/images/decal/retro/picnic.png
  data/levels/misc/menu_retro.stl
  data/levels/revenge_in_redmond/antarctica.stl
  data/levels/revenge_in_redmond/get_to_choppa.stl
  data/levels/revenge_in_redmond/info
  data/levels/revenge_in_redmond/intro.stl
  data/levels/revenge_in_redmond/intro.txt
  data/levels/revenge_in_redmond/long_office_nights.stl
  data/levels/revenge_in_redmond/outro.stl
  data/levels/revenge_in_redmond/outro.txt
  data/levels/revenge_in_redmond/redmond_headquarters.stl
  data/levels/revenge_in_redmond/where_my_super_cape.stl
  data/levels/revenge_in_redmond/who_is_gown.stl
  data/levels/revenge_in_redmond/worldmap.stwm
  data/music/retro/theme_old.music
  data/music/retro/theme_old.ogg
Labels: type:patch, type:level, category:levels, status:needs-review

#2810 Fix some Tux animation glitches
  src/object/player.cpp
Labels: status:in-progress, category:code, type:bugfix
