Repository SuperTux/supertux, pull requests merged in 2024-12, with the labels that each got.

#3124 Compress `TileMap` tiles in level file
  src/editor/object_option.cpp
  src/object/tilemap.cpp
  src/object/tilemap.hpp
  src/util/reader_mapping.cpp
  src/util/reader_mapping.hpp
  src/util/writer.cpp
  src/util/writer.hpp
  tests/reader_test.cpp
Labels: involves:performance, category:code, status:needs-review

#3060 Fix max drop height on slopes (part 2)
  src/badguy/badguy.cpp
  src/badguy/badguy.hpp
  src/badguy/walking_badguy.cpp
  src/badguy/walking_badguy.hpp
  src/collision/collision_system.cpp
  src/collision/collision_system.hpp
  src/math/aatriangle.hpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
Labels: type:patch, status:in-progress, category:code

#2993 Replace asserts with clamping in color constructor
  src/video/color.cpp
Labels: priority:low, category:code, status:needs-review

#3149 Debug option to hide player HUD (including `LevelTime` counter)
  src/object/level_time.cpp
  src/supertux/debug.cpp
  src/supertux/debug.hpp
  src/supertux/menu/debug_menu.cpp
  src/supertux/player_status_hud.cpp
Labels: type:feature, category:code, status:needs-review

#3158 Support X/Y position periods for autotile "alt-id"s
  data/images/autotiles.satc
  src/supertux/autotile.cpp
  src/supertux/autotile.hpp
  src/supertux/autotile_parser.cpp
Labels: type:feature, category:code, status:needs-review
