Repository SuperTux/supertux, pull requests merged in 2024-09, with the labels that each got.

#2967 Let bouncing snowball turn around on collision with other badguys
  src/badguy/bouncing_snowball.cpp
  src/badguy/bouncing_snowball.hpp
Labels: type:patch, involves:functionality, category:code, status:needs-review

#2812 Fix max drop height on slopes
  src/badguy/badguy.cpp
  src/badguy/badguy.hpp
  src/badguy/walking_badguy.cpp
  src/badguy/walking_badguy.hpp
  src/collision/collision_system.cpp
  src/collision/collision_system.hpp
  src/math/aatriangle.hpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
Labels: priority:medium, status:in-progress, category:code, type:bugfix

#2624 Zeekling behaviour improvements
  data/images/creatures/zeekling/charge-0.png
  data/images/creatures/zeekling/charge-1.png
  data/images/creatures/zeekling/charge-2.png
  data/images/creatures/zeekling/charge-3.png
  data/images/creatures/zeekling/charge-4.png
  data/images/creatures/zeekling/dive-0.png
  src/badguy/zeekling.cpp
  src/badguy/zeekling.hpp
  src/math/util.hpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
Labels: priority:medium, involves:functionality, type:feature, category:code, status:needs-review

#3063 Toggling level statistics
  src/supertux/level.cpp
  src/supertux/level.hpp
  src/supertux/level_parser.cpp
  src/supertux/levelintro.cpp
  src/supertux/menu/editor_level_menu.cpp
  src/supertux/statistics.cpp
  src/supertux/statistics.hpp
  src/worldmap/worldmap_sector.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review
