Repository SuperTux/supertux, pull requests merged in 2024-04, with the labels that each got.

#2838 Fix sliding player clipping through floor
  src/object/player.cpp
Labels: category:code, status:needs-review, involves:physics, type:bugfix

#2835 Fix some frozen enemy bugs
  data/images/creatures/bag/bag.sprite
  data/images/creatures/bsod/bsod.sprite
  data/images/creatures/dive_mine/dive_mine.sprite
  data/images/creatures/fatbat/fatbat.sprite
  data/images/creatures/fish/forest/bluefish.sprite
  data/images/creatures/fish/forest/brownfish.sprite
  data/images/creatures/fish/forest/jumpfish.sprite
  data/images/creatures/fish/ice/bluefish.sprite
  data/images/creatures/fish/ice/goldfish.sprite
  data/images/creatures/fish/ice/greenfish.sprite
  data/images/creatures/gold_bomb/gold_bomb.sprite
  data/images/creatures/haywire/haywire.sprite
  data/images/creatures/igel/corrupted/corrupted_igel.sprite
  data/images/creatures/igel/igel.sprite
  data/images/creatures/jumpy/corruptjumpy.sprite
  data/images/creatures/jumpy/metaljumpy.sprite
  data/images/creatures/jumpy/snowjumpy.sprite
  data/images/creatures/jumpy/woodjumpy.sprite
  data/images/creatures/laptop/laptop.sprite
  data/images/creatures/mr_bomb/mr_bomb.sprite
  data/images/creatures/mr_bomb/old_bomb/old_bomb.sprite
  data/images/creatures/mr_candle/mr-candle.sprite
  data/images/creatures/mr_tree/corrupted/haunted_tree.sprite
  data/images/creatures/mr_tree/mr_tree.sprite
  data/images/creatures/mr_tree/stumpy.sprite
  data/images/creatures/owl/owl.sprite
  data/images/creatures/pumpkin/bumpkin.sprite
  data/images/creatures/pumpkin/pumpkin.sprite
  data/images/creatures/short_fuse/short_fuse.sprite
  data/images/creatures/skydive/skydive.sprite
  data/images/creatures/snail/corrupted/corrupted_snail.sprite
  data/images/creatures/snail/snail.sprite
  data/images/creatures/spiky/sleepingspiky.sprite
  data/images/creatures/spiky/spiky.sprite
  data/images/creatures/vicious_ivy/corrupted/rotten_ivy.sprite
  data/images/creatures/vicious_ivy/vicious_ivy.sprite
  data/images/creatures/walkingleaf/corrupted/rotten_leaf.sprite
  data/images/creatures/walkingleaf/walkingleaf.sprite
  data/images/creatures/zeekling/zeekling.sprite
  src/badguy/badguy.cpp
  src/badguy/bouncing_snowball.hpp
  src/badguy/dive_mine.cpp
  src/badguy/fish_chasing.cpp
  src/badguy/fish_jumping.cpp
  src/badguy/fish_swimming.cpp
Labels: involves:functionality, category:code, status:needs-review, type:bugfix

#2847 Remove unnecessary randomness of mole
  src/badguy/mole.cpp
  src/badguy/mole.hpp
Labels: type:patch, involves:functionality, category:code, status:needs-review

#2850 Fix bouncing snowball bouncing pattern
  src/badguy/bouncing_snowball.cpp
Labels: involves:functionality, category:code, status:needs-review, type:bugfix

#2888 Fix mole dying twice
  src/badguy/mole.cpp
Labels: category:code, status:needs-review, type:bugfix

#2858 Update snail behavior to be more consistent
  src/badguy/snail.cpp
Labels: type:patch, involves:functionality, category:code, status:needs-review, type:bugfix

#2865 Jump to path node immediately
  src/object/path_walker.cpp
  src/object/path_walker.hpp
  src/object/platform.cpp
  src/object/platform.hpp
  src/object/tilemap.cpp
  src/object/tilemap.hpp
  src/scripting/platform.cpp
  src/scripting/tilemap.cpp
Labels: type:feature, category:code, status:needs-review

#2844 Door and teleport improvements
  data/scripts/default.nut
  src/object/camera.hpp
  src/object/infoblock.cpp
  src/object/player.cpp
  src/object/player.hpp
  src/scripting/level.cpp
  src/scripting/level.hpp
  src/scripting/wrapper.cpp
  src/supertux/game_session.cpp
  src/supertux/game_session.hpp
  src/supertux/screen_fade.hpp
  src/supertux/screen_manager.cpp
  src/supertux/sector.cpp
  src/supertux/sector.hpp
  src/supertux/shrinkfade.cpp
  src/supertux/shrinkfade.hpp
  src/trigger/door.cpp
  src/trigger/door.hpp
  src/worldmap/worldmap_sector.cpp
Labels: involves:functionality, type:feature, category:code, status:needs-review

#2868 Fix player in title screen jumping slopes
  src/supertux/title_screen.cpp
Labels: category:code, status:needs-review, type:bugfix

#2813 Editor zooming
  src/editor/editor.cpp
  src/editor/editor.hpp
  src/editor/overlay_widget.cpp
  src/editor/toolbox_widget.cpp
  src/editor/util.cpp
  src/editor/util.hpp
  src/object/camera.cpp
  src/object/camera.hpp
  src/supertux/menu/editor_menu.cpp
Labels: involves:editor, type:feature, category:code, status:needs-review

#2854 Fix crusher issues
  src/badguy/crusher.cpp
  src/collision/collision_system.cpp
  src/object/rock.cpp
Labels: category:code, status:needs-review, type:bugfix

#2913 Fix error when given debug, optimized, or general keyword...
  mk/cmake/SuperTux/ProvidePhysfs.cmake
  mk/cmake/SuperTux/ProvideSDL2_ttf.cmake
Labels: os:windows, type:patch

#2886 Fix swimming on slopes
  src/collision/collision_system.cpp
Labels: category:code, status:needs-review, type:bugfix

#2862 Prevent corrupted big granito from dying twice
  src/badguy/corrupted_granito_big.cpp
Labels: category:code, status:needs-review, type:bugfix

#2878 Create physfsutil::get_last_error
  src/addon/addon_manager.cpp
  src/addon/downloader.cpp
  src/audio/sound_file.cpp
  src/editor/particle_editor.cpp
  src/physfs/ifile_streambuf.cpp
  src/physfs/ofile_streambuf.cpp
  src/physfs/physfs_sdl.cpp
  src/physfs/util.cpp
  src/physfs/util.hpp
  src/supertux/level.cpp
  src/supertux/main.cpp
  src/supertux/profile.cpp
  src/supertux/world.cpp
Labels: type:patch, category:code, status:needs-review
