Repository SuperTux/supertux, pull requests merged in 2024-03, with the labels that each got.

#2807 Fix camera following tux when dying
  src/object/camera.cpp
Labels: involves:functionality, category:code, status:needs-review, type:bugfix

#2805 ST OST - Updated Icy Island Midday theme
  data/music/midday.ogg
Labels: status:needs-review

#2824 Fix cannon showing wrong action with auto direction
  data/images/creatures/dispenser/cannon.sprite
  src/badguy/dispenser.cpp
  src/badguy/dispenser.hpp
Labels: involves:functionality, category:code, type:bugfix

#2819 Custom layer option for `MovingSprite`
  src/object/moving_sprite.cpp
  src/object/moving_sprite.hpp
Labels: type:feature, category:code, status:needs-review

#2804 Do not increment powerup counter on restart_level()
  src/object/player.cpp
  src/object/player.hpp
  src/supertux/game_session.cpp
Labels: category:code, status:needs-review, type:bugfix

#2822 Fix building on MSYS2 (CLANG64)
  CMakeLists.txt
  mk/cmake/SuperTux/ProvideSDL2.cmake
Labels: type:patch, status:needs-review

#2823 ST OST - Yet more songs for the Icy Island
  data/AUTHORS
  data/music/antarctic/glacier.music
  data/music/antarctic/glacier.ogg
  data/music/antarctic/snowfort.music
  data/music/antarctic/snowfort.ogg
  data/music/antarctic/yetiboss.music
  data/music/antarctic/yetiboss.ogg
  data/music/castle/icecastle.music
  data/music/castle/icecastle.ogg
Labels: status:needs-review

#2859 Fix lightning strikes
  src/object/thunderstorm.cpp
  src/object/thunderstorm.hpp
Labels: type:bugfix
